name: CI / Deploy to GHCR

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  call-ghcr-workflow:
    uses: offensive-vk/Assets/.github/workflows/ghcr.yml@master
    with:
      author: "Vedansh"
      title: "auto-pr-action"
      description: "Github Action to Create Pull Requests Automatically on Push Event."
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}